export interface Country {
  name: string;
  code: string;
}

export const AVAILABLE_COUNTRIES: Country[] = [
  { name: 'Afeganistão', code: 'af' },
  { name: 'Albânia', code: 'al' },
  { name: 'Argélia', code: 'dz' },
  { name: 'Andorra', code: 'ad' },
  { name: 'Angola', code: 'ao' },
  { name: 'Antígua e Barbuda', code: 'ag' },
  { name: 'Argentina', code: 'ar' },
  { name: 'Armênia', code: 'am' },
  { name: 'Austrália', code: 'au' },
  { name: 'Áustria', code: 'at' },
  { name: 'Azerbaijão', code: 'az' },
  { name: 'Bahamas', code: 'bs' },
  { name: 'Bahrein', code: 'bh' },
  { name: 'Bangladesh', code: 'bd' },
  { name: 'Barbados', code: 'bb' },
  { name: 'Bélgica', code: 'be' },
  { name: 'Belize', code: 'bz' },
  { name: 'Benin', code: 'bj' },
  { name: 'Butão', code: 'bt' },
  { name: 'Bolívia', code: 'bo' },
  { name: 'Bósnia e Herzegovina', code: 'ba' },
  { name: 'Botsuana', code: 'bw' },
  { name: 'Brasil', code: 'br' },
  { name: 'Brunei', code: 'bn' },
  { name: 'Bulgária', code: 'bg' },
  { name: 'Burkina Faso', code: 'bf' },
  { name: 'Burundi', code: 'bi' },
  { name: 'Cabo Verde', code: 'cv' },
  { name: 'Camboja', code: 'kh' },
  { name: 'Camarões', code: 'cm' },
  { name: 'Canadá', code: 'ca' },
  { name: 'República Centro-Africana', code: 'cf' },
  { name: 'Chade', code: 'td' },
  { name: 'Chile', code: 'cl' },
  { name: 'China', code: 'cn' },
  { name: 'Colômbia', code: 'co' },
  { name: 'Comores', code: 'km' },
  { name: 'Congo (Brazzaville)', code: 'cg' },
  { name: 'Congo (Kinshasa)', code: 'cd' },
  { name: 'Costa Rica', code: 'cr' },
  { name: 'Croácia', code: 'hr' },
  { name: 'Cuba', code: 'cu' },
  { name: 'Chipre', code: 'cy' },
  { name: 'República Tcheca', code: 'cz' },
  { name: 'Dinamarca', code: 'dk' },
  { name: 'Djibuti', code: 'dj' },
  { name: 'Dominica', code: 'dm' },
  { name: 'República Dominicana', code: 'do' },
  { name: 'Equador', code: 'ec' },
  { name: 'Egito', code: 'eg' },
  { name: 'El Salvador', code: 'sv' },
  { name: 'Guiné Equatorial', code: 'gq' },
  { name: 'Eritreia', code: 'er' },
  { name: 'Estônia', code: 'ee' },
  { name: 'Eswatini', code: 'sz' },
  { name: 'Etiópia', code: 'et' },
  { name: 'Fiji', code: 'fj' },
  { name: 'Finlândia', code: 'fi' },
  { name: 'França', code: 'fr' },
  { name: 'Gabão', code: 'ga' },
  { name: 'Gâmbia', code: 'gm' },
  { name: 'Gana', code: 'gh' },
  { name: 'Grécia', code: 'gr' },
  { name: 'Granada', code: 'gd' },
  { name: 'Guatemala', code: 'gt' },
  { name: 'Guiné', code: 'gn' },
  { name: 'Guiné-Bissau', code: 'gw' },
  { name: 'Guiana', code: 'gy' },
  { name: 'Haiti', code: 'ht' },
  { name: 'Honduras', code: 'hn' },
  { name: 'Hungria', code: 'hu' },
  { name: 'Islândia', code: 'is' },
  { name: 'Índia', code: 'in' },
  { name: 'Indonésia', code: 'id' },
  { name: 'Irã', code: 'ir' },
  { name: 'Iraque', code: 'iq' },
  { name: 'Irlanda', code: 'ie' },
  { name: 'Israel', code: 'il' },
  { name: 'Itália', code: 'it' },
  { name: 'Jamaica', code: 'jm' },
  { name: 'Japão', code: 'jp' },
  { name: 'Jordânia', code: 'jo' },
  { name: 'Cazaquistão', code: 'kz' },
  { name: 'Quênia', code: 'ke' },
  { name: 'Kiribati', code: 'ki' },
  { name: 'Coreia do Sul', code: 'kr' },
  { name: 'Kuwait', code: 'kw' },
  { name: 'Quirguistão', code: 'kg' },
  { name: 'Laos', code: 'la' },
  { name: 'Letônia', code: 'lv' },
  { name: 'Líbano', code: 'lb' },
  { name: 'Lesoto', code: 'ls' },
  { name: 'Libéria', code: 'lr' },
  { name: 'Líbia', code: 'ly' },
  { name: 'Liechtenstein', code: 'li' },
  { name: 'Lituânia', code: 'lt' },
  { name: 'Luxemburgo', code: 'lu' },
  { name: 'Madagáscar', code: 'mg' },
  { name: 'Maláui', code: 'mw' },
  { name: 'Maldivas', code: 'mv' },
  { name: 'Malásia', code: 'my' },
  { name: 'Malta', code: 'mt' },
  { name: 'Ilhas Marshall', code: 'mh' },
  { name: 'Mauritânia', code: 'mr' },
  { name: 'Maurício', code: 'mu' },
  { name: 'México', code: 'mx' },
  { name: 'Micronésia', code: 'fm' },
  { name: 'Moldávia', code: 'md' },
  { name: 'Mônaco', code: 'mc' },
  { name: 'Mongólia', code: 'mn' },
  { name: 'Montenegro', code: 'me' },
  { name: 'Marrocos', code: 'ma' },
  { name: 'Moçambique', code: 'mz' },
  { name: 'Myanmar', code: 'mm' },
  { name: 'Namíbia', code: 'na' },
  { name: 'Nauru', code: 'nr' },
  { name: 'Nepal', code: 'np' },
  { name: 'Países Baixos', code: 'nl' },
  { name: 'Nova Zelândia', code: 'nz' },
  { name: 'Nicarágua', code: 'ni' },
  { name: 'Níger', code: 'ne' },
  { name: 'Nigéria', code: 'ng' },
  { name: 'Coreia do Norte', code: 'kp' },
  { name: 'Noruega', code: 'no' },
  { name: 'Omã', code: 'om' },
  { name: 'Paquistão', code: 'pk' },
  { name: 'Palau', code: 'pw' },
  { name: 'Palestina', code: 'ps' },
  { name: 'Panamá', code: 'pa' },
  { name: 'Papua-Nova Guiné', code: 'pg' },
  { name: 'Paraguai', code: 'py' },
  { name: 'Peru', code: 'pe' },
  { name: 'Filipinas', code: 'ph' },
  { name: 'Polônia', code: 'pl' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Catar', code: 'qa' },
  { name: 'Romênia', code: 'ro' },
  { name: 'Rússia', code: 'ru' },
  { name: 'Ruanda', code: 'rw' },
  { name: 'São Cristóvão e Nevis', code: 'kn' },
  { name: 'Santa Lúcia', code: 'lc' },
  { name: 'São Vicente e Granadinas', code: 'vc' },
  { name: 'Samoa', code: 'ws' },
  { name: 'San Marino', code: 'sm' },
  { name: 'São Tomé e Príncipe', code: 'st' },
  { name: 'Arábia Saudita', code: 'sa' },
  { name: 'Senegal', code: 'sn' },
  { name: 'Sérvia', code: 'rs' },
  { name: 'Seychelles', code: 'sc' },
  { name: 'Serra Leoa', code: 'sl' },
  { name: 'Singapura', code: 'sg' },
  { name: 'Eslováquia', code: 'sk' },
  { name: 'Eslovênia', code: 'si' },
  { name: 'Ilhas Salomão', code: 'sb' },
  { name: 'Somália', code: 'so' },
  { name: 'África do Sul', code: 'za' },
  { name: 'Sudão do Sul', code: 'ss' },
  { name: 'Espanha', code: 'es' },
  { name: 'Sri Lanka', code: 'lk' },
  { name: 'Sudão', code: 'sd' },
  { name: 'Suriname', code: 'sr' },
  { name: 'Suécia', code: 'se' },
  { name: 'Suíça', code: 'ch' },
  { name: 'Síria', code: 'sy' },
  { name: 'Tajiquistão', code: 'tj' },
  { name: 'Tanzânia', code: 'tz' },
  { name: 'Tailândia', code: 'th' },
  { name: 'Timor-Leste', code: 'tl' },
  { name: 'Togo', code: 'tg' },
  { name: 'Tonga', code: 'to' },
  { name: 'Trindade e Tobago', code: 'tt' },
  { name: 'Tunísia', code: 'tn' },
  { name: 'Turquia', code: 'tr' },
  { name: 'Turcomenistão', code: 'tm' },
  { name: 'Tuvalu', code: 'tv' },
  { name: 'Uganda', code: 'ug' },
  { name: 'Ucrânia', code: 'ua' },
  { name: 'Emirados Árabes Unidos', code: 'ae' },
  { name: 'Reino Unido', code: 'gb' },
  { name: 'Estados Unidos', code: 'us' },
  { name: 'Uruguai', code: 'uy' },
  { name: 'Uzbequistão', code: 'uz' },
  { name: 'Vanuatu', code: 'vu' },
  { name: 'Vaticano', code: 'va' },
  { name: 'Venezuela', code: 've' },
  { name: 'Vietnã', code: 'vn' },
  { name: 'Iémen', code: 'ye' },
  { name: 'Zâmbia', code: 'zm' },
  { name: 'Zimbábue', code: 'zw' }
];