export const SIDEBAR_COLOR = {
  SIDEBAR_BT_COLOR: '#EFBF04',
  SIDEBAR_COLOR: '#2B2B2B',
  SIDEBAR_LN_COLOR: '#EFBF04',
  SIDEBAR_BT_COLOR_HOVER: '#856A00',
  SIDEBAR_TXT_COLOR: '#fff',
  SIDEBAR_ICON_COLOR: '#fff',
};